# Generated by Django 3.0.8 on 2020-07-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default='dsUuns', max_length=6, unique=True)),
                ('redirect', models.URLField(max_length=255)),
            ],
        ),
    ]
