# Generated by Django 3.0.8 on 2020-07-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulrshortner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='slug',
            field=models.CharField(default='HCAPQA', max_length=6, unique=True),
        ),
    ]
