# Generated by Django 3.0.8 on 2020-07-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulrshortner', '0002_auto_20200714_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='slug',
            field=models.CharField(default='arA8hj', max_length=6, unique=True),
        ),
    ]
