# Generated by Django 3.0.8 on 2020-07-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulrshortner', '0004_auto_20200715_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='hits',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='urls',
            name='slug',
            field=models.CharField(default='wFLnhD', max_length=6, unique=True),
        ),
    ]
