# Generated by Django 3.0.8 on 2020-07-15 21:28

from django.db import migrations
import randomslugfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ulrshortner', '0005_auto_20200715_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='slug',
            field=randomslugfield.fields.RandomSlugField(blank=True, editable=False, length=6, max_length=6, unique=True),
        ),
    ]
